' Copyright 2013-2014 CS Systèmes d'Information
' Licensed to CS Systèmes d'Information (CS) under one or more
' contributor license agreements.  See the NOTICE file distributed with
' this work for additional information regarding copyright ownership.
' CS licenses this file to You under the Apache License, Version 2.0
' (the "License"); you may not use this file except in compliance with
' the License.  You may obtain a copy of the License at
'
'   http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml

  skinparam svek                                true
  skinparam NoteBackgroundColor                 #F3EFEB
  skinparam NoteBorderColor                     #691616
  skinparam NoteFontColor                       #691616
  skinparam SequenceActorBorderColor            #6A584B
  skinparam SequenceParticipantBackgroundColor  #F3EFEB/CCC9C5
  skinparam SequenceParticipantBorderColor      #6A584B
  skinparam SequenceLifeLineBackgroundColor     #CCC9C5/F3EFEB
  skinparam SequenceLifeLineBorderColor         #6A584B
  skinparam SequenceArrowColor                  #6A584B
  skinparam SequenceBorderColor                 #6A584B
  skinparam SequenceFontSize                    11

  hide footbox

  participant "Application" as A
  participant "Interface" as I
  participant "Rugged" as R
  participant "Orekit" as O

  activate A
    A -> I : init
    activate I
      I -> I : loadModels
      I -> R : initiliaze(sensors, ephemeris)
      activate R
        R -> R : unfoldOpticalPath(sensors)
        activate R
          R -> O : composeTransforms
          activate O
            O --> R : sensors transforms
          deactivate O
        deactivate R
       R -> O : createPropagator(ephemeris)
         activate O
           O --> R : interpolating propagator
          deactivate O
       R -> O : createTransformProvider(sensors transforms, propagator)
         activate O
           O --> R : combined TransformProvider with caching feature
         deactivate O
      deactivate R
      I -> R : registerLineTimeStampingModel
      activate R
      deactivate R
      I -> R : registerDEMCallback
      activate R
      deactivate R
    deactivate I
  deactivate A

@enduml
