' Copyright 2013-2017 CS Systèmes d'Information
' Licensed to CS Systèmes d'Information (CS) under one or more
' contributor license agreements.  See the NOTICE file distributed with
' this work for additional information regarding copyright ownership.
' CS licenses this file to You under the Apache License, Version 2.0
' (the "License"); you may not use this file except in compliance with
' the License.  You may obtain a copy of the License at
'
'   http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml

  skinparam svek                                true
  skinparam NoteBackgroundColor                 #F3EFEB
  skinparam NoteBorderColor                     #691616
  skinparam NoteFontColor                       #691616
  skinparam SequenceActorBorderColor            #6A584B
  skinparam SequenceActorBackgroundColor        #F3EFEB/CCC9C5
  skinparam SequenceParticipantBackgroundColor  #F3EFEB/CCC9C5
  skinparam SequenceParticipantBorderColor      #6A584B
  skinparam SequenceLifeLineBackgroundColor     #CCC9C5/F3EFEB
  skinparam SequenceLifeLineBorderColor         #6A584B
  skinparam SequenceArrowColor                  #6A584B
  skinparam SequenceBorderColor                 #6A584B
  skinparam SequenceFontSize                    11

  hide footbox

  actor       "UserMain" as A
  participant "MissionSpecificDEM" as B
  participant "Rugged" as R
  participant "ExtendedEllipsoid" as E
  participant "SpacecraftToObservedBody" as S
  participant "LineSensor" as LS
  participant "Orekit" as O

  activate A
    A -> A : loadModels
    A -> B : create
    activate B
    deactivate B
    A -> A : unfoldOpticalPath
    activate A
    deactivate A
    A -> R : create(DEM, algorithm, frames, ellipsoid, ephemeris)
    activate R
      R -> E : create
      activate E
      deactivate E
      R -> O : createProviders(ephemeris)
      activate O
        O --> R : position/velocity/atttitude providers
      deactivate O
      R -> S : create
      activate S
      deactivate S
    deactivate R
    A -> LS : create
    activate LS
    deactivate LS
    A -> R : addLineSensor
    activate R
    deactivate R
    A -> LS : create
    activate LS
    deactivate LS
    A -> R : addLineSensor
    activate R
    deactivate R
    A -> LS : create
    activate LS
    deactivate LS
    A -> R : addLineSensor
    activate R
    deactivate R
  deactivate A

@enduml
